# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: check-uv-lock
        name: check uv lock
        entry: "just lock-check"
        language: system
        pass_filenames: false
      - id: check-ruff
        name: check ruff standard
        entry: "just check-ruff"
        language: system
        pass_filenames: false
      - id: check-mypy
        name: check mypy typing
        entry: "just check-mypy"
        language: system
        pass_filenames: false
